### ISSUE TITLE
Puzzel

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#15]
![image](https://github.com/user-attachments/assets/adf1b2c5-1fe7-4522-8415-9645ab432934)

I assume the order has something to do with the sequence near the teleport pad but in the sequense doesn't change there BUT the actual sequence is always different.

**Comment by Nintai** [comment]
The sequence does matter, but its the statues above (stacking from 1 to 5).
<img width="203" alt="image" src="https://github.com/user-attachments/assets/34e9f301-d872-4ffa-be09-f5573e9d7192">

**Comment by ChalkyBrush** [comment]
is this a  bug 🤔

**Comment by supremeorb2** [comment]
got it, i'm just stupid
XD
