### ISSUE TITLE
Creating a new char in legend

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#20]
So I entered Tanari Encampment with my high lvl char on legend difficulty, then i went back to Tanari beaches and quit to menu to create a new char.

This new char was somehow in legend:
<img width="701" alt="image" src="https://github.com/user-attachments/assets/3573036d-62fd-49ea-958b-9b534867f97b">

**Comment by ChalkyBrush** [comment]
fixed
