### ISSUE TITLE
Water Mage Robe doesn't work too close to water

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#24]
<img width="346" alt="image" src="https://github.com/user-attachments/assets/673575a5-b209-4e99-99ed-4951172146c7">

The waves dont seem to work if you are standing anywhere too close to the water surface (height-wise)

While i can accept the fact that waves dont work in water, because... logic, but there seems to be a place where it should work, but doesnt:
<img width="829" alt="image" src="https://github.com/user-attachments/assets/2b975265-cde4-42c4-8999-b62931477adc">
<img width="888" alt="image" src="https://github.com/user-attachments/assets/2d8b39f8-70d5-4157-b70b-7c13abd0911d">

**Comment by ChalkyBrush** [comment]
fixed
