### ISSUE TITLE
Auriun - Dealing dmg while dead

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#25]
<img width="338" alt="image" src="https://github.com/user-attachments/assets/5aa77985-ed5c-4298-960a-1d0375213b3a">

Seraphic vest will activate even while you are dead, which will in turn trigger E2:
<img width="405" alt="image" src="https://github.com/user-attachments/assets/d7b833c4-d304-4f11-a169-0ea6dce1d55c">

So you can just run into big groups of enemies and die, and then wait until they are all dead

**Comment by ChalkyBrush** [comment]
🤪
