### ISSUE TITLE
Legend save progress reset bug - Hunter rank

### ISSUE THREAD

**Issue by ghost3211** [ChalkyBrush/Roshpit2-BugTracker#27]
Proceeding from D rank to C rank then going to the portal to reenter legend instance will completely wipe off all progress on that instance of gameplay and return to the save point prior to entering portal.

**Comment by ChalkyBrush** [comment]
have you experienced this on the latest version?

**Comment by ghost3211** [comment]
Yes, just tested again and it still persists

**Comment by ChalkyBrush** [comment]
should be fixed now

**Comment by ChalkyBrush** [comment]
seems fixed, closing for now
