### ISSUE TITLE
+ level stats on items

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#29]
+ level skill works for both sub abilites and core.
+ level Talent only works for core.

not sure if one is broken or this is intentially, personally i would prefer if + talents could effect sub, it'd add an extra set of complexity

**Comment by ChalkyBrush** [comment]
Actually intended -> if +talents worked on sub abilities it would be too easy to reach high level talents from other classes. + Ability level points are rare enough that it doesn't cause any issue
