### ISSUE TITLE
Spirit Warrior - [Mobility] Ancient Spirit. Enemy Skill Targeting Behavior.

### ISSUE THREAD

**Issue by silenciaco** [ChalkyBrush/Roshpit2-BugTracker#35]
While the spirit itself does not seem to hold aggro (dealing dmg with the spirit aura seems to direct aggro towards the player), enemies will still cast skills towards the spirit itself if the player is not within their range. This is most noticeable with like the shield bashers etc.

They probably should be ignoring the spirit entirely targeting wise.

**Comment by ChalkyBrush** [comment]
👍

**Comment by ChalkyBrush** [comment]
Ai handler now ignores "invulnerable" units when seeking a target
