### ISSUE TITLE
Bladeslinger Boots - Blocked by water surface

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#43]
Bladeslinger boots wont hit enemies in water most of the time because the projectile is destroyed when the surface is hit:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/bb136c77-9d81-4a4a-b445-aa87f92efa8b">

Ofc this also means they do nothing at all when in shallow water

**Comment by ChalkyBrush** [comment]
fixed
