### ISSUE TITLE
Ability icon on lobby

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#45]
![image](https://github.com/user-attachments/assets/9a845a1f-e62d-4ebe-8dfb-93600696449f)

Bricked icon at character selection

**Comment by Nintai** [comment]
Happened to me after i played a venomort with conjuror's Q socketed in E slot. Went to the menu, wanted to create a new char and was on Conjuror:
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/0e7188b5-824d-4f92-8246-7c514c818162">

**Comment by GoToNightmare** [comment]
It seems like items with sub abilities is a problem
