### ISSUE TITLE
Free Quest reward rerolls

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#46]
If you complete a quest with the targeted reward (e.g. Orgoth'Sol one where you get 2 legendary weapons to choose from) and you dont like the rewards, you can just close the reward screen by clicking the chest icon in the bottom left:
<img width="175" alt="image" src="https://github.com/user-attachments/assets/37a385dd-6c4e-4dbd-aafc-a4c70755a009">

Then, if you turn in another quest, the reward will be queued:
1. Legendary Weapon
2. ???? Reward

But upon entering the queue, it will reroll the reward for the first quest in the queue. So you can in theory just repeatedly finish a repeatable quest to reroll the legendary item as often as you have unfinished quests, and enemies to finish the quests.

**Comment by GoToNightmare** [comment]
Fixed
