### ISSUE TITLE
Enchanter's Garb - Cant trigger multiple times with Far Seer Glove

### ISSUE THREAD

**Issue by Nintai** [ChalkyBrush/Roshpit2-BugTracker#47]
Using Enchanter's Garb:
<img width="339" alt="image" src="https://github.com/user-attachments/assets/211a9256-7a43-45f7-8298-1db2f5151975">

With Far Seer Glove:
<img width="337" alt="image" src="https://github.com/user-attachments/assets/7aa00f40-08c7-4a13-a343-85c4f72c6fd3">

Will only trigger Garb once:
<img width="748" alt="image" src="https://github.com/user-attachments/assets/d95b0364-c707-465b-8df3-81b2e057f74a">

I guess you made it trigger only once per attack, to prevent melee to trigger on multiple enemies on one attack, but maybe we can somehow make it work with far seer glove? 

Or at least change the description to say "Can only trigger once per attack"

**Comment by ChalkyBrush** [comment]
intended, sorry sir 😁
