### ISSUE TITLE
Bladestorm movement

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#53]
If you cast your bladestorm and stay still, you will stay still.
If you cast your blade storm and then press any movement, and then stop pressing it, you will in bladestorm slowly move in that direction even when pressing nothing

**Comment by ChalkyBrush** [comment]
it's intentional though 🤭 

~~ bladestorm lowers your "kinetic friction" so you decelerate slower 😁 ~~

**Comment by supremeorb2** [comment]
You never stop moving, you don't decelerate slower, you just move at a very slow pace in the given direction


https://github.com/user-attachments/assets/b46fa40e-f57f-4bed-91c6-9c74509e2dce

**Comment by ChalkyBrush** [comment]
![image](https://github.com/user-attachments/assets/ab9791b3-4049-4f8e-9798-d54ebac47800)

**Comment by ChalkyBrush** [comment]
ya I was wrong in initial post, it's not the kinetic friction, the buff keeps you moving with an override adding its own additional velocity
