### ISSUE TITLE
This subability is not working, can't see it in tooltips and if it is working, not noticeable.

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#66]
The cds are the same, and doesn't feel like they're getting accelerated either
![image](https://github.com/user-attachments/assets/396ea5cb-3f1c-448e-ad66-297cf005aed1)

**Comment by GoToNightmare** [comment]
Just checked and it works.
This modifier reduces **active cooldowns only** (when ability is on cooldown), its not a generic cdr.

![image](https://github.com/user-attachments/assets/aab91b36-629a-4acb-91c9-af4967f5392f)

Thanks for reports 😊

**Comment by supremeorb2** [comment]
I understand, but it's just very hard to verify game side tbh, and i did check when things were on cooldown btw.

**Comment by GoToNightmare** [comment]
Maybe description is not clear enough 🤔
