### ISSUE TITLE
Name of NPC showing wrong

### ISSUE THREAD

**Issue by supremeorb2** [ChalkyBrush/Roshpit2-BugTracker#9]
![image](https://github.com/user-attachments/assets/a5d254ed-e3f5-4c3a-9bde-5a46953b93e8)

Name
![image_2024-09-06_132252387](https://github.com/user-attachments/assets/6c53e1e4-4e9c-439b-b8cb-bf1ad16332e6)

**Comment by supremeorb2** [comment]
lol whoops didn't mean to do that twice
but yeah name issue

**Comment by ChalkyBrush** [comment]
fixd
